# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Main_Window(object):
    def setupUi(self, Login_Main_Window):
        Login_Main_Window.setObjectName("Login_Main_Window")
        Login_Main_Window.resize(1440, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login_Main_Window.sizePolicy().hasHeightForWidth())
        Login_Main_Window.setSizePolicy(sizePolicy)
        Login_Main_Window.setMinimumSize(QtCore.QSize(1440, 900))
        Login_Main_Window.setMaximumSize(QtCore.QSize(1440, 900))
        Login_Main_Window.setStyleSheet("background-color: rgb(14, 88, 100);")
        self.centralwidget = QtWidgets.QWidget(Login_Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.create_account_frame = QtWidgets.QFrame(self.Main_Frame)
        self.create_account_frame.setGeometry(QtCore.QRect(490, 120, 460, 681))
        self.create_account_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 30px; \n"
"border: 2px;")
        self.create_account_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_account_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_account_frame.setObjectName("create_account_frame")
        self.lbl_create_account = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_create_account.setGeometry(QtCore.QRect(0, 40, 461, 61))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_create_account.setFont(font)
        self.lbl_create_account.setStyleSheet("color: rgb(44, 39, 56);")
        self.lbl_create_account.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_create_account.setObjectName("lbl_create_account")
        self.lbl_password = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_password.setGeometry(QtCore.QRect(30, 420, 351, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_password.setFont(font)
        self.lbl_password.setObjectName("lbl_password")
        self.btn_create_account = QtWidgets.QPushButton(self.create_account_frame)
        self.btn_create_account.setGeometry(QtCore.QRect(30, 560, 399, 52))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        self.btn_create_account.setFont(font)
        self.btn_create_account.setStyleSheet("background-color: rgb(8, 128, 174);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 128, 174);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.btn_create_account.setObjectName("btn_create_account")
        self.edit_enter_password = QtWidgets.QLineEdit(self.create_account_frame)
        self.edit_enter_password.setGeometry(QtCore.QRect(30, 452, 399, 52))
        self.edit_enter_password.setStyleSheet("background-color: rgb(219, 226, 234);\n"
"border-color: rgb(219, 226, 234);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.edit_enter_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_enter_password.setCursorPosition(0)
        self.edit_enter_password.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_enter_password.setObjectName("edit_enter_password")
        self.lbl_error_placeholder = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_error_placeholder.setGeometry(QtCore.QRect(30, 630, 421, 20))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        self.lbl_error_placeholder.setFont(font)
        self.lbl_error_placeholder.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_error_placeholder.setObjectName("lbl_error_placeholder")
        self.lbl_password_2 = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_password_2.setGeometry(QtCore.QRect(30, 120, 351, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_password_2.setFont(font)
        self.lbl_password_2.setObjectName("lbl_password_2")
        self.edit_enter_password_2 = QtWidgets.QLineEdit(self.create_account_frame)
        self.edit_enter_password_2.setGeometry(QtCore.QRect(30, 152, 399, 52))
        self.edit_enter_password_2.setStyleSheet("background-color: rgb(219, 226, 234);\n"
"border-color: rgb(219, 226, 234);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.edit_enter_password_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_enter_password_2.setCursorPosition(0)
        self.edit_enter_password_2.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_enter_password_2.setObjectName("edit_enter_password_2")
        self.lbl_password_3 = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_password_3.setGeometry(QtCore.QRect(30, 320, 351, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_password_3.setFont(font)
        self.lbl_password_3.setObjectName("lbl_password_3")
        self.edit_enter_password_3 = QtWidgets.QLineEdit(self.create_account_frame)
        self.edit_enter_password_3.setGeometry(QtCore.QRect(30, 352, 399, 52))
        self.edit_enter_password_3.setStyleSheet("background-color: rgb(219, 226, 234);\n"
"border-color: rgb(219, 226, 234);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.edit_enter_password_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_enter_password_3.setCursorPosition(0)
        self.edit_enter_password_3.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_enter_password_3.setObjectName("edit_enter_password_3")
        self.lbl_password_4 = QtWidgets.QLabel(self.create_account_frame)
        self.lbl_password_4.setGeometry(QtCore.QRect(30, 220, 351, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_password_4.setFont(font)
        self.lbl_password_4.setObjectName("lbl_password_4")
        self.edit_enter_password_4 = QtWidgets.QLineEdit(self.create_account_frame)
        self.edit_enter_password_4.setGeometry(QtCore.QRect(30, 252, 399, 52))
        self.edit_enter_password_4.setStyleSheet("background-color: rgb(219, 226, 234);\n"
"border-color: rgb(219, 226, 234);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.edit_enter_password_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edit_enter_password_4.setCursorPosition(0)
        self.edit_enter_password_4.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_enter_password_4.setObjectName("edit_enter_password_4")
        self.btn_back_button = QtWidgets.QPushButton(self.Main_Frame)
        self.btn_back_button.setGeometry(QtCore.QRect(40, 10, 81, 71))
        self.btn_back_button.setStyleSheet("background: transparent;")
        self.btn_back_button.setText("")
        self.btn_back_button.setFlat(True)
        self.btn_back_button.setObjectName("btn_back_button")
        self.lbl_back_button = QtWidgets.QLabel(self.Main_Frame)
        self.lbl_back_button.setGeometry(QtCore.QRect(40, 10, 81, 71))
        self.lbl_back_button.setText("")
        self.lbl_back_button.setPixmap(QtGui.QPixmap("Images/Navigtaion - Back Button - Default - Rest.png"))
        self.lbl_back_button.setScaledContents(True)
        self.lbl_back_button.setObjectName("lbl_back_button")
        self.create_account_frame.raise_()
        self.lbl_back_button.raise_()
        self.btn_back_button.raise_()
        self.gridLayout.addWidget(self.Main_Frame, 0, 1, 1, 1)
        Login_Main_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login_Main_Window)
        self.statusbar.setObjectName("statusbar")
        Login_Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Login_Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Main_Window)

    def retranslateUi(self, Login_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Main_Window.setWindowTitle(_translate("Login_Main_Window", "Create an Account"))
        self.lbl_create_account.setText(_translate("Login_Main_Window", "Create an account."))
        self.lbl_password.setText(_translate("Login_Main_Window", "Confirm Password"))
        self.btn_create_account.setText(_translate("Login_Main_Window", "Login"))
        self.edit_enter_password.setPlaceholderText(_translate("Login_Main_Window", "**************"))
        self.lbl_error_placeholder.setText(_translate("Login_Main_Window", "Error message placeholder text."))
        self.lbl_password_2.setText(_translate("Login_Main_Window", "Full Name"))
        self.edit_enter_password_2.setPlaceholderText(_translate("Login_Main_Window", "Name"))
        self.lbl_password_3.setText(_translate("Login_Main_Window", "Password"))
        self.edit_enter_password_3.setPlaceholderText(_translate("Login_Main_Window", "**************"))
        self.lbl_password_4.setText(_translate("Login_Main_Window", "Email Address"))
        self.edit_enter_password_4.setPlaceholderText(_translate("Login_Main_Window", "youremail@domain.co(m).uk"))
# import pyqt_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Main_Window = QtWidgets.QMainWindow()
    ui = Ui_Login_Main_Window()
    ui.setupUi(Login_Main_Window)
    Login_Main_Window.show()
    sys.exit(app.exec_())
