# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Main_Window(object):
    def setupUi(self, Login_Main_Window):
        Login_Main_Window.setObjectName("Login_Main_Window")
        Login_Main_Window.resize(1440, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login_Main_Window.sizePolicy().hasHeightForWidth())
        Login_Main_Window.setSizePolicy(sizePolicy)
        Login_Main_Window.setMinimumSize(QtCore.QSize(1440, 900))
        Login_Main_Window.setMaximumSize(QtCore.QSize(1440, 900))
        Login_Main_Window.setStyleSheet("background-color: rgb(14, 88, 100);")
        self.centralwidget = QtWidgets.QWidget(Login_Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.login_frame = QtWidgets.QFrame(self.Main_Frame)
        self.login_frame.setGeometry(QtCore.QRect(490, 208, 460, 485))
        self.login_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 30px; \n"
"border: 2px;")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.lbl_enter_details = QtWidgets.QLabel(self.login_frame)
        self.lbl_enter_details.setGeometry(QtCore.QRect(0, 40, 461, 61))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_enter_details.setFont(font)
        self.lbl_enter_details.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_enter_details.setObjectName("lbl_enter_details")
        self.name_frame = QtWidgets.QFrame(self.login_frame)
        self.name_frame.setGeometry(QtCore.QRect(60, 120, 349, 86))
        self.name_frame.setStyleSheet("background-color: rgb(54, 210, 189);\n"
"border-color: rgb(54, 210, 189);\n"
"border-radius: 20px; \n"
"border: 2px;")
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.lbl_username = QtWidgets.QLabel(self.name_frame)
        self.lbl_username.setGeometry(QtCore.QRect(10, 20, 330, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_username.setFont(font)
        self.lbl_username.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_username.setIndent(0)
        self.lbl_username.setObjectName("lbl_username")
        self.lbl_password = QtWidgets.QLabel(self.login_frame)
        self.lbl_password.setGeometry(QtCore.QRect(30, 250, 351, 31))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_password.setFont(font)
        self.lbl_password.setObjectName("lbl_password")
        self.btn_login = QtWidgets.QPushButton(self.login_frame)
        self.btn_login.setGeometry(QtCore.QRect(30, 380, 399, 52))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color: rgb(8, 128, 174);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(8, 128, 174);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.btn_login.setObjectName("btn_login")
        self.edit_enter_password = QtWidgets.QLineEdit(self.login_frame)
        self.edit_enter_password.setGeometry(QtCore.QRect(30, 282, 399, 52))
        self.edit_enter_password.setStyleSheet("border-color: rgb(219, 226, 234);\n"
"background-color: rgb(219, 226, 234);\n"
"border-radius: 5px; \n"
"border: 2px;")
        self.edit_enter_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_enter_password.setCursorPosition(0)
        self.edit_enter_password.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_enter_password.setObjectName("edit_enter_password")
        self.lbl_error_placeholder = QtWidgets.QLabel(self.login_frame)
        self.lbl_error_placeholder.setGeometry(QtCore.QRect(30, 448, 421, 20))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        self.lbl_error_placeholder.setFont(font)
        self.lbl_error_placeholder.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_error_placeholder.setObjectName("lbl_error_placeholder")
        self.btn_back_button = QtWidgets.QPushButton(self.Main_Frame)
        self.btn_back_button.setGeometry(QtCore.QRect(40, 10, 81, 71))
        self.btn_back_button.setStyleSheet("background: transparent;")
        self.btn_back_button.setText("")
        self.btn_back_button.setFlat(True)
        self.btn_back_button.setObjectName("btn_back_button")
        self.lbl_back_button = QtWidgets.QLabel(self.Main_Frame)
        self.lbl_back_button.setGeometry(QtCore.QRect(40, 10, 81, 71))
        self.lbl_back_button.setText("")
        self.lbl_back_button.setPixmap(QtGui.QPixmap("Images/Navigtaion - Back Button - Default - Rest.png"))
        self.lbl_back_button.setScaledContents(True)
        self.lbl_back_button.setObjectName("lbl_back_button")
        self.gridLayout.addWidget(self.Main_Frame, 0, 0, 1, 1)
        Login_Main_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login_Main_Window)
        self.statusbar.setObjectName("statusbar")
        Login_Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Login_Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Main_Window)

    def retranslateUi(self, Login_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Main_Window.setWindowTitle(_translate("Login_Main_Window", "Login"))
        self.lbl_enter_details.setText(_translate("Login_Main_Window", "Enter your login details."))
        self.lbl_username.setText(_translate("Login_Main_Window", "Placeholder Name"))
        self.lbl_password.setText(_translate("Login_Main_Window", "Password"))
        self.btn_login.setText(_translate("Login_Main_Window", "Login"))
        self.edit_enter_password.setPlaceholderText(_translate("Login_Main_Window", "**************"))
        self.lbl_error_placeholder.setText(_translate("Login_Main_Window", "Error message placeholder text."))
# import pyqt_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Main_Window = QtWidgets.QMainWindow()
    ui = Ui_Login_Main_Window()
    ui.setupUi(Login_Main_Window)
    Login_Main_Window.show()
    sys.exit(app.exec_())
